# Generated by Django 6.0.3 on 2026-03-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='apellido',
            new_name='apellido_materno',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='apellido',
            new_name='apellido_materno',
        ),
        migrations.AddField(
            model_name='doctor',
            name='apellido_paterno',
            field=models.CharField(default='Desconocido', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='apellido_paterno',
            field=models.CharField(default='Desconocido', max_length=50),
            preserve_default=False,
        ),
    ]
